### ISSUE TITLE
Panel layout need to be review for the Y coord. of jacks

### ISSUE THREAD

**Issue by waynechen16** [TOILmodular/EurorackOTAVCF#3]
The previous panel issue cannot be reopened. So I create a new ticket here.

The Y coordinate seems still not right. It should be higher than the current value (2~3mm). The X coordinate is correct.

![IMG_1307](https://user-images.githubusercontent.com/6702452/223384624-4ec59e47-c922-410f-8ce1-406fb382039b.jpg)

**Comment by TOILmodular** [comment]
Not sure, why you still see incorrect coordinates, but the values were adjusted. Left side should be 12.5mm, instead of 11mm. Right side should be 27.5mm, instead of 29. Maybe my update did not yet show up, when you checked after my first reply. Please check again. I see the right values.

**Comment by waynechen16** [comment]
Yes, 12.5mm and 27.5mm are the right value for X coord. After checking, the Y coordinates are all aligned. The previously missed alignment in Y-axis should be caused by the tilted placement of the panel. It's my mistake. It's now all correct. Thank you very much for sharing!
